service: serverless-project

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  stackName: my-lambda-${self:provider.stage}


functions:
  hello:
    handler: handler.server
    name: ${self:provider.stage}-mylambda
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger (creates an API-GW)
          path: /
          method: any
          cors: true
          private: false # No API-Key 
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: any
          cors: true
          private: false
    iamRoleStatementsName: GetCsvDataS3
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: arn:aws:s3:::mediumbucket-manuel/* 
